name = Press
description = A layout demonstrating the newspapaper style layout.
preview = preview.png
template = press-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[help]           = Help
regions[content]       = Content
regions[column_one]     = Column Left one
regions[column_two]     = Column Center one
regions[column_three]   = Column Center two
regions[column_four]    = Column right one
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/press/press.layout.css

; Scripts
scripts[] = layouts/press/assets/press.js
